// Template/React_Next/Admin/src/pages/other/sample-page.tsx
import React, { ReactElement } from "react";
import BreadcrumbItem from "@common/BreadcrumbItem";
import Layout from "@layout/index";
import { Card, Col, Row } from "react-bootstrap";

const SamplePage = () => {
    return (
        <>
            <BreadcrumbItem mainTitle="Other" subTitle="Sample Page" />
            <Row>
                <Col sm={12}>
                    <Card>
                        <div className="card-header">
                        <h5>Hello card</h5>
                        </div>
                        <Card.Body>
                        </Card.Body>
                    </Card>
                </Col>
            </Row>
        </>
    )
}

SamplePage.getLayout = (page: ReactElement) => {
    return (
        <Layout>
            {page}
        </Layout>
    )
};

export default SamplePage;

// Template/Vue/Starterkit/src/views/live-preview/other/sample-page.vue
<script>
import Layout from "@/layout/main.vue"
import pageheader from "@/components/page-header.vue"

export default {
    name: "SAMPLE-PAGE",
    components: {
        Layout, pageheader
    }
}
</script>

<template>
    <Layout>
        <pageheader title="Sample Page" pageTitle="Other" />

        <BRow>
            <BCol sm="12">
                <BCard no-body>
                    <BCardHeader>
                        <h5>Hello card</h5>
                    </BCardHeader>
                    <BCardBody>
                    </BCardBody>
                </BCard>
            </BCol>
        </BRow>
    </Layout>
</template>
