// Template/Vue/Starterkit/src/views/live-preview/ui-kit/affiliate-dashboard.vue
<script>
import Layout from "@/layout/main.vue"
import pageheader from "@/components/page-header.vue"

export default {
    name: "AFFILIATE DASHBOARD",
    components: {
        Layout, pageheader
    },
}
</script>

<template>
    <Layout>
        <pageheader title="Affiliate Dashboard" pageTitle="Ui kit" />
        <BRow>
            <div class="col-md-12 col-xxl-4">
                <div class="card statistics-card-1">
                    <div class="card-body">
                        <img src="@/assets/images/widget/img-status-2.svg" alt="img" class="img-fluid img-bg">
                        <div class="d-flex align-items-center">
                            <div class="avtar bg-brand-color-1 text-white me-3">
                                <i class="ph-duotone ph-currency-dollar f-26"></i>
                            </div>
                            <div>
                                <p class="text-muted mb-0">Referrals</p>
                                <div class="d-flex align-items-end">
                                    <h2 class="mb-0 f-w-500"><span class="text-muted">$</span> 134.6 <small
                                            class="text-muted">k</small></h2>
                                    <span class="badge bg-light-success ms-2"><i class="ti ti-chevrons-up"></i> 55%</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-xxl-4">
                <div class="card statistics-card-1">
                    <div class="card-body">
                        <img src="@/assets/images/widget/img-status-1.svg" alt="img" class="img-fluid img-bg">
                        <div class="d-flex align-items-center">
                            <div class="avtar bg-brand-color-2 text-white me-3">
                                <i class="ph-duotone ph-scales f-26"></i>
                            </div>
                            <div>
                                <p class="text-muted mb-0">Conversion Rate</p>
                                <div class="d-flex align-items-end">
                                    <h2 class="mb-0 f-w-500">8.57<small class="text-muted">%</small></h2>
                                    <span class="badge bg-light-danger ms-2"><i class="ti ti-chevrons-down"></i> 3.6%</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-xxl-4">
                <div class="card statistics-card-1">
                    <div class="card-body">
                        <img src="@/assets/images/widget/img-status-3.svg" alt="img" class="img-fluid img-bg">
                        <div class="d-flex align-items-center">
                            <div class="avtar bg-brand-color-3 text-white me-3">
                                <i class="ph-duotone ph-users-four f-26"></i>
                            </div>
                            <div>
                                <p class="text-muted mb-0">Visits</p>
                                <div class="d-flex align-items-end">
                                    <h2 class="mb-0 f-w-500">278</h2>
                                    <span class="badge bg-light-success ms-2"><i class="ti ti-chevrons-up"></i> 7%</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <BCard no-body class="card table-card">
                    <div class="card-header">
                        <h5>Affiliates</h5>
                    </div>
                    <div class="card-body py-3 px-0 pb-0">
                        <div class="table-responsive affiliate-table">
                            <table class="table table-hover table-borderless mb-0">
                                <tbody>
                                    <tr>
                                        <td>
                                            <div class="d-flex align-items-center">
                                                <img src="@/assets/images/user/avatar-2.jpg" alt=""
                                                    class="img-fluid wid-30 rounded-1">
                                                <h6 class="mb-0 ms-2">John Doe</h6>
                                            </div>
                                        </td>
                                        <td>Dashboard</td>
                                        <td class="text-end f-w-600">$38</td>
                                        <td><i class="ti ti-arrow-up text-success f-18 align-text-bottom"></i> 5.8%</td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div class="d-flex align-items-center">
                                                <img src="@/assets/images/user/avatar-1.jpg" alt=""
                                                    class="img-fluid wid-30 rounded-1">
                                                <h6 class="mb-0 ms-2">Keefs</h6>
                                            </div>
                                        </td>
                                        <td>New Website</td>
                                        <td class="text-end f-w-600">$928</td>
                                        <td><i class="ti ti-arrow-down text-danger f-18 align-text-bottom"></i> 51.2%</td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div class="d-flex align-items-center">
                                                <img src="@/assets/images/user/avatar-3.jpg" alt=""
                                                    class="img-fluid wid-30 rounded-1">
                                                <h6 class="mb-0 ms-2">Lazaro</h6>
                                            </div>
                                        </td>
                                        <td>Dashboard</td>
                                        <td class="text-end f-w-600">$674</td>
                                        <td><i class="ti ti-arrow-up text-success f-18 align-text-bottom"></i> 17.1%</td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div class="d-flex align-items-center">
                                                <img src="@/assets/images/user/avatar-4.jpg" alt=""
                                                    class="img-fluid wid-30 rounded-1">
                                                <h6 class="mb-0 ms-2">Adeline</h6>
                                            </div>
                                        </td>
                                        <td>New Website</td>
                                        <td class="text-end f-w-600">$1,438</td>
                                        <td><i class="ti ti-arrow-down text-danger f-18 align-text-bottom"></i> 15.8%</td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div class="d-flex align-items-center">
                                                <img src="@/assets/images/user/avatar-5.jpg" alt=""
                                                    class="img-fluid wid-30 rounded-1">
                                                <h6 class="mb-0 ms-2">John Doe</h6>
                                            </div>
                                        </td>
                                        <td>Invoice</td>
                                        <td class="text-end f-w-600">$90</td>
                                        <td><i class="ti ti-arrow-up text-success f-18 align-text-bottom"></i> 9.8%</td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div class="d-flex align-items-center">
                                                <img src="@/assets/images/user/avatar-6.jpg" alt=""
                                                    class="img-fluid wid-30 rounded-1">
                                                <h6 class="mb-0 ms-2">Keefs</h6>
                                            </div>
                                        </td>
                                        <td>Dashboard</td>
                                        <td class="text-end f-w-600">$123</td>
                                        <td><i class="ti ti-arrow-up text-success f-18 align-text-bottom"></i> 5.8%</td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div class="d-flex align-items-center">
                                                <img src="@/assets/images/user/avatar-7.jpg" alt=""
                                                    class="img-fluid wid-30 rounded-1">
                                                <h6 class="mb-0 ms-2">Lazaro</h6>
                                            </div>
                                        </td>
                                        <td>Landing page</td>
                                        <td class="text-end f-w-600">$928</td>
                                        <td><i class="ti ti-arrow-down text-danger f-18 align-text-bottom"></i> 51.2%</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </BCard>
            </div>
            <div class="col-md-6">
                <div class="card table-card">
                    <div class="card-header">
                        <h5>Top Visitors</h5>
                    </div>
                    <div class="card-body py-3 px-0 pb-0">
                        <div class="table-responsive">
                            <table class="table table-hover table-borderless mb-0">
                                <tbody>
                                    <tr>
                                        <td>
                                            <div class="d-flex align-items-center">
                                                <img src="@/assets/images/user/avatar-4.jpg" alt=""
                                                    class="img-fluid wid-30 rounded-1">
                                                <h6 class="mb-0 ms-2">Adeline</h6>
                                            </div>
                                        </td>
                                        <td class="text-end f-w-600">$1,438</td>
                                        <td><i class="ti ti-arrow-down text-danger f-18 align-text-bottom"></i> 15.8%</td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div class="d-flex align-items-center">
                                                <img src="@/assets/images/user/avatar-5.jpg" alt=""
                                                    class="img-fluid wid-30 rounded-1">
                                                <h6 class="mb-0 ms-2">John Doe</h6>
                                            </div>
                                        </td>
                                        <td class="text-end f-w-600">$90</td>
                                        <td><i class="ti ti-arrow-up text-success f-18 align-text-bottom"></i> 9.8%</td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div class="d-flex align-items-center">
                                                <img src="@/assets/images/user/avatar-6.jpg" alt=""
                                                    class="img-fluid wid-30 rounded-1">
                                                <h6 class="mb-0 ms-2">Keefs</h6>
                                            </div>
                                        </td>
                                        <td class="text-end f-w-600">$123</td>
                                        <td><i class="ti ti-arrow-up text-success f-18 align-text-bottom"></i> 5.8%</td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div class="d-flex align-items-center">
                                                <img src="@/assets/images/user/avatar-7.jpg" alt=""
                                                    class="img-fluid wid-30 rounded-1">
                                                <h6 class="mb-0 ms-2">Lazaro</h6>
                                            </div>
                                        </td>
                                        <td class="text-end f-w-600">$928</td>
                                        <td><i class="ti ti-arrow-down text-danger f-18 align-text-bottom"></i> 51.2%</td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div class="d-flex align-items-center">
                                                <img src="@/assets/images/user/avatar-2.jpg" alt=""
                                                    class="img-fluid wid-30 rounded-1">
                                                <h6 class="mb-0 ms-2">John Doe</h6>
                                            </div>
                                        </td>
                                        <td class="text-end f-w-600">$38</td>
                                        <td><i class="ti ti-arrow-up text-success f-18 align-text-bottom"></i> 5.8%</td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div class="d-flex align-items-center">
                                                <img src="@/assets/images/user/avatar-1.jpg" alt=""
                                                    class="img-fluid wid-30 rounded-1">
                                                <h6 class="mb-0 ms-2">Keefs</h6>
                                            </div>
                                        </td>
                                        <td class="text-end f-w-600">$928</td>
                                        <td><i class="ti ti-arrow-down text-danger f-18 align-text-bottom"></i> 51.2%</td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div class="d-flex align-items-center">
                                                <img src="@/assets/images/user/avatar-3.jpg" alt=""
                                                    class="img-fluid wid-30 rounded-1">
                                                <h6 class="mb-0 ms-2">Lazaro</h6>
                                            </div>
                                    </td>
                                    <td class="text-end f-w-600">$674</td>
                                    <td><i class="ti ti-arrow-up text-success f-18 align-text-bottom"></i> 17.1%</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </BRow>
</Layout></template>

// Template/React_Next/Admin/src/pages/affiliate-dashboard.tsx
import BreadcrumbItem from "@common/BreadcrumbItem";
import Layout from "@layout/index";
import React, { ReactElement } from "react";
import { affiliateWidget, affiliateData, topVisitorData } from "@data/index";
import { Card, Col, Row } from "react-bootstrap";
import Image from "next/image";

const AffiliateDashboard = () => {
  return (
    <>
      <BreadcrumbItem mainTitle="Dashboard" subTitle="Affiliate Dashboard" />
      <Row>
        {(affiliateWidget || []).map((item, key) => (
          <Col md={12} xxl={4} key={key}>
            <Card className="statistics-card-1">
              <Card.Body>
                <Image src={item.cardImg} alt="img" className="img-fluid img-bg" />
                <div className="d-flex align-items-center">
                  <div className={"avtar " + item.iconColor + " text-white me-3"}>
                    <i className={item.icon}></i>
                  </div>
                  <div>
                    <p className="text-muted mb-0">{item.title}</p>
                    <div className="d-flex align-items-end">
                      <h2 className="mb-0 f-w-500">{item.suffix && item.suffix}
                        {item.price}
                        {item.prefix && item.prefix}</h2>
                      <span className={"badge bg-light-" + item.badgeColor + " ms-2"}>
                        <i className="ti ti-chevrons-up"></i> {item.percentage}%
                      </span>
                    </div>
                  </div>
                </div>
              </Card.Body>
            </Card>
          </Col>
        ))}

        <Col md={6}>
          <Card className="table-card">
            <div className="card-header">
              <h5>Affiliates</h5>
            </div>
            <Card.Body className="py-3 px-0">
              <div className="table-responsive affiliate-table">
                <table className="table table-hover table-borderless mb-0">
                  <tbody>

                    {(affiliateData || []).map((item, key) => (
                      <tr key={key}>
                        <td>
                          <div className="d-flex align-items-center">
                            <Image src={item.img} alt="" className="img-fluid wid-30 rounded-1" />
                            <h6 className="mb-0 ms-2">{item.name}</h6>
                          </div>
                        </td>
                        <td>{item.subTitle}</td>
                        <td className="text-end f-w-600">${item.price}</td>
                        <td><i className={item.arrowUp ? "ti ti-arrow-up text-success f-18 align-text-bottom" : "ti ti-arrow-down text-danger f-18 align-text-bottom"}></i>
                          {item.percentage}%</td>
                      </tr>
                    ))}

                  </tbody>
                </table>
              </div>
            </Card.Body>
          </Card>
        </Col>

        <Col md={6}>
          <Card className="table-card">
            <div className="card-header">
              <h5>Top Visitors</h5>
            </div>
            <Card.Body className="py-3 px-0">
              <div className="table-responsive affiliate-table">
                <table className="table table-hover table-borderless mb-0">
                  <tbody>

                    {(topVisitorData || []).map((item, key) => (
                      <tr key={key}>
                        <td>
                          <div className="d-flex align-items-center">
                            <Image src={item.img} alt="" className="img-fluid wid-30 rounded-1" />
                            <h6 className="mb-0 ms-2">{item.name}</h6>
                          </div>
                        </td>
                        {/* <td>{item.subTitle}</td> */}
                        <td className="text-end f-w-600">${item.price}</td>
                        <td><i className={item.arrowUp ? "ti ti-arrow-up text-success f-18 align-text-bottom" : "ti ti-arrow-down text-danger f-18 align-text-bottom"}></i>
                          {item.percentage}%</td>
                      </tr>
                    ))}

                  </tbody>
                </table>
              </div>
            </Card.Body>
          </Card>
        </Col>
      </Row>
    </>
  );
};

AffiliateDashboard.getLayout = (page: ReactElement) => {
  return (
    <Layout>
      {page}
    </Layout>
  );
};


export default AffiliateDashboard;
