// Template/Vue/Admin/src/views/live-preview/application/plans.vue
<script>
import Layout from "@/layout/main.vue"
// import simplebar from "simplebar-vue"
export default {
    name: "Plans",
    components: {
        Layout, //simplebar
    },
}
</script>

<template>
    <Layout>
        <BRow>
            <div class="col-sm-12">
                <div class="row align-items-center justify-content-center mb-4">
                    <div class="col-auto">
                        <label for="swc-price" class="h4 mb-0">Annual</label>
                    </div>
                    <div class="col-auto">
                        <div class="form-check form-switch p-0 m-0">
                            <input class="form-check-input f-20 m-0 postion-relative" type="checkbox" role="switch" id="swc-price" checked>
                        </div>
                    </div>
                    <div class="col-auto">
                        <label for="swc-price" class="h4 mb-0">Monthly</label>
                    </div>
                </div>
                <div class="collapse multi-collapse" id="pricemonth">
                    <div class="row">
                        <div class="col-md-6 col-xxl-3">
                            <div class="card price-card">
                                <div class="card-body price-head bg-light-primary">
                                    <h5 class="text-primary">Lite</h5>
                                    <h2 class="price-price text-primary">$0 <span>/month</span></h2>
                                    <div class="price-icon bg-light-primary">
                                        <i class="ph-duotone ph-rocket text-primary"></i>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <ul class="list-unstyled product-list">
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>Free domains</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>CDN Integration</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>Advanced Settings</li>
                                        <li>100,000 unique users</li>
                                        <li>2000 Items</li>
                                        <li>API Access</li>
                                        <li>Search Features</li>
                                        <li>Editor personalization</li>
                                        <li>Upload special sites</li>
                                        <li>Advanced Features</li>
                                    </ul>
                                    <div class="d-grid">
                                        <button class="btn btn-primary">Current Plan</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-xxl-3">
                            <div class="card price-card">
                                <div class="card-body price-head bg-light-secondary">
                                    <h5 class="text-secondary">Standard</h5>
                                    <h2 class="price-price text-secondary">$9 <span>/month</span></h2>
                                    <div class="price-icon bg-light-secondary">
                                        <i class="ph-duotone ph-grains text-secondary"></i>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <ul class="list-unstyled product-list">
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>Free domains</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>CDN Integration</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>Advanced Settings</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>100,000 unique users</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>2000 Items</li>
                                        <li>API Access</li>
                                        <li>Search Features</li>
                                        <li>Editor personalization</li>
                                        <li>Upload special sites</li>
                                        <li>Advanced Features</li>
                                    </ul>
                                    <div class="d-grid">
                                        <button class="btn btn-outline-secondary">Upgrade Plan</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-xxl-3">
                            <div class="card price-card">
                                <div class="card-body price-head bg-light-secondary">
                                    <h5 class="text-secondary">Standard</h5>
                                    <h2 class="price-price text-secondary">$36 <span>/month</span></h2>
                                    <div class="price-icon bg-light-secondary">
                                        <i class="ph-duotone ph-flower-lotus text-secondary"></i>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <ul class="list-unstyled product-list">
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>Free domains</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>CDN Integration</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>Advanced Settings</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>100,000 unique users</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>2000 Items</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>API Access</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>Search Features</li>
                                        <li>Editor personalization</li>
                                        <li>Upload special sites</li>
                                        <li>Advanced Features</li>
                                    </ul>
                                    <div class="d-grid">
                                        <button class="btn btn-outline-secondary">Upgrade Plan</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-xxl-3">
                            <div class="card price-card">
                                <div class="card-body price-head bg-light-secondary">
                                    <h5 class="text-secondary">ENTERPRISE</h5>
                                    <h2 class="price-price text-secondary">$69 <span>/month</span></h2>
                                    <div class="price-icon bg-light-secondary">
                                        <i class="ph-duotone ph-buildings text-secondary"></i>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <ul class="list-unstyled product-list">
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>Free domains</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>CDN Integration</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>Advanced Settings</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>100,000 unique users</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>2000 Items</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>API Access</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>Search Features</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>Editor personalization</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>Upload special sites</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>Advanced Features</li>
                                    </ul>
                                    <div class="d-grid">
                                        <button class="btn btn-outline-secondary">Upgrade Plan</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="collapse multi-collapse" id="priceyear">
                    <div class="row">
                        <div class="col-md-6 col-xxl-3">
                            <div class="card price-card">
                                <div class="card-body price-head bg-light-primary">
                                    <h5 class="text-primary">Lite</h5>
                                    <h2 class="price-price text-primary">$120 <span>/year</span></h2>
                                    <div class="price-icon bg-light-primary">
                                        <i class="ph-duotone ph-rocket text-primary"></i>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <ul class="list-unstyled product-list">
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>Free domains</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>CDN Integration</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>Advanced Settings</li>
                                        <li>100,000 unique users</li>
                                        <li>2000 Items</li>
                                        <li>API Access</li>
                                        <li>Search Features</li>
                                        <li>Editor personalization</li>
                                        <li>Upload special sites</li>
                                        <li>Advanced Features</li>
                                    </ul>
                                    <div class="d-grid">
                                        <button class="btn btn-primary">Current Plan</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-xxl-3">
                            <div class="card price-card">
                                <div class="card-body price-head bg-light-secondary">
                                    <h5 class="text-secondary">Standard</h5>
                                    <h2 class="price-price text-secondary">$99 <span>/year</span></h2>
                                    <div class="price-icon bg-light-secondary">
                                        <i class="ph-duotone ph-grains text-secondary"></i>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <ul class="list-unstyled product-list">
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>Free domains</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>CDN Integration</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>Advanced Settings</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>100,000 unique users</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>2000 Items</li>
                                        <li>API Access</li>
                                        <li>Search Features</li>
                                        <li>Editor personalization</li>
                                        <li>Upload special sites</li>
                                        <li>Advanced Features</li>
                                    </ul>
                                    <div class="d-grid">
                                        <button class="btn btn-outline-secondary">Upgrade Plan</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-xxl-3">
                            <div class="card price-card">
                                <div class="card-body price-head bg-light-secondary">
                                    <h5 class="text-secondary">Standard</h5>
                                    <h2 class="price-price text-secondary">$1236 <span>/year</span></h2>
                                    <div class="price-icon bg-light-secondary">
                                        <i class="ph-duotone ph-flower-lotus text-secondary"></i>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <ul class="list-unstyled product-list">
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>Free domains</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>CDN Integration</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>Advanced Settings</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>100,000 unique users</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>2000 Items</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>API Access</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>Search Features</li>
                                        <li>Editor personalization</li>
                                        <li>Upload special sites</li>
                                        <li>Advanced Features</li>
                                    </ul>
                                    <div class="d-grid">
                                        <button class="btn btn-outline-secondary">Upgrade Plan</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-xxl-3">
                            <div class="card price-card">
                                <div class="card-body price-head bg-light-secondary">
                                    <h5 class="text-secondary">ENTERPRISE</h5>
                                    <h2 class="price-price text-secondary">$3469 <span>/year</span></h2>
                                    <div class="price-icon bg-light-secondary">
                                        <i class="ph-duotone ph-buildings text-secondary"></i>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <ul class="list-unstyled product-list">
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>Free domains</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>CDN Integration</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>Advanced Settings</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>100,000 unique users</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>2000 Items</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>API Access</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>Search Features</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>Editor personalization</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>Upload special sites</li>
                                        <li class="enable"><i class="ph-duotone ph-check-circle"></i>Advanced Features</li>
                                    </ul>
                                    <div class="d-grid">
                                        <button class="btn btn-outline-secondary">Upgrade Plan</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </BRow>
    </Layout>
</template>

// Template/React_Next/Admin/src/pages/ui-kit/plans.tsx
import BreadcrumbItem from "@common/BreadcrumbItem";
import Layout from "@layout/index";
import React, { ReactElement } from "react";
import { Card, Col, Row } from "react-bootstrap";

const Plans = () => {
    return (
       <>
        <BreadcrumbItem mainTitle="Ui kit" subTitle="Plans"  />
        <Row>
        <Col sm={12}>
          <Row className="align-items-center justify-content-center mb-4">
            <div className="col-auto">
              <label htmlFor="swc-price" className="h4 mb-0">Annual</label>
            </div>
            <div className="col-auto">
              <div className="form-check form-switch p-0 m-0">
                <input className="form-check-input f-20 m-0 postion-relative" type="checkbox" role="switch" id="swc-price" />
              </div>
            </div>
            <div className="col-auto">
              <label htmlFor="swc-price" className="h4 mb-0">Monthly</label>
            </div>
          </Row>
          <Row>
            <Col md={6} xxl={3}>
              <Card className="price-card">
                <Card.Body className="price-head bg-light-primary">
                  <h5 className="text-primary">Lite</h5>
                  <h2 className="price-price text-primary">$0 <span>/month</span></h2>
                  <div className="price-icon bg-light-primary">
                    <i className="ph-duotone ph-rocket text-primary"></i>
                  </div>
                </Card.Body>
                <Card.Body>
                  <ul className="list-unstyled product-list">
                    <li className="enable"><i className="ph-duotone ph-check-circle"></i>Free domains</li>
                    <li className="enable"><i className="ph-duotone ph-check-circle"></i>CDN Integration</li>
                    <li className="enable"><i className="ph-duotone ph-check-circle"></i>Advanced Settings</li>
                    <li>100,000 unique users</li>
                    <li>2000 Items</li>
                    <li>API Access</li>
                    <li>Search Features</li>
                    <li>Editor personalization</li>
                    <li>Upload special sites</li>
                    <li>Advanced Features</li>
                  </ul>
                  <div className="d-grid">
                    <button className="btn btn-primary">Current Plan</button>
                  </div>
                </Card.Body>
              </Card>
            </Col>
            <Col md={6} xxl={3}>
              <Card className="price-card">
                <Card.Body className="price-head bg-light-secondary">
                  <h5 className="text-secondary">Standard</h5>
                  <h2 className="price-price text-secondary">$9 <span>/month</span></h2>
                  <div className="price-icon bg-light-secondary">
                    <i className="ph-duotone ph-grains text-secondary"></i>
                  </div>
                </Card.Body>
                <Card.Body>
                  <ul className="list-unstyled product-list">
                    <li className="enable"><i className="ph-duotone ph-check-circle"></i>Free domains</li>
                    <li className="enable"><i className="ph-duotone ph-check-circle"></i>CDN Integration</li>
                    <li className="enable"><i className="ph-duotone ph-check-circle"></i>Advanced Settings</li>
                    <li className="enable"><i className="ph-duotone ph-check-circle"></i>100,000 unique users</li>
                    <li className="enable"><i className="ph-duotone ph-check-circle"></i>2000 Items</li>
                    <li>API Access</li>
                    <li>Search Features</li>
                    <li>Editor personalization</li>
                    <li>Upload special sites</li>
                    <li>Advanced Features</li>
                  </ul>
                  <div className="d-grid">
                    <button className="btn btn-outline-secondary">Upgrade Plan</button>
                  </div>
                </Card.Body>
              </Card>
            </Col>
            <Col md={6} xxl={3}>
              <Card className="price-card">
                <Card.Body className="price-head bg-light-secondary">
                  <h5 className="text-secondary">Standard</h5>
                  <h2 className="price-price text-secondary">$36 <span>/month</span></h2>
                  <div className="price-icon bg-light-secondary">
                    <i className="ph-duotone ph-flower-lotus text-secondary"></i>
                  </div>
                </Card.Body>
                <Card.Body>
                  <ul className="list-unstyled product-list">
                    <li className="enable"><i className="ph-duotone ph-check-circle"></i>Free domains</li>
                    <li className="enable"><i className="ph-duotone ph-check-circle"></i>CDN Integration</li>
                    <li className="enable"><i className="ph-duotone ph-check-circle"></i>Advanced Settings</li>
                    <li className="enable"><i className="ph-duotone ph-check-circle"></i>100,000 unique users</li>
                    <li className="enable"><i className="ph-duotone ph-check-circle"></i>2000 Items</li>
                    <li className="enable"><i className="ph-duotone ph-check-circle"></i>API Access</li>
                    <li className="enable"><i className="ph-duotone ph-check-circle"></i>Search Features</li>
                    <li>Editor personalization</li>
                    <li>Upload special sites</li>
                    <li>Advanced Features</li>
                  </ul>
                  <div className="d-grid">
                    <button className="btn btn-outline-secondary">Upgrade Plan</button>
                  </div>
                </Card.Body>
              </Card>
            </Col>
            <Col md={6} xxl={3}>
              <Card className="price-card">
                <Card.Body className="price-head bg-light-secondary">
                  <h5 className="text-secondary">ENTERPRISE</h5>
                  <h2 className="price-price text-secondary">$69 <span>/month</span></h2>
                  <div className="price-icon bg-light-secondary">
                    <i className="ph-duotone ph-buildings text-secondary"></i>
                  </div>
                </Card.Body>
                <Card.Body>
                  <ul className="list-unstyled product-list">
                    <li className="enable"><i className="ph-duotone ph-check-circle"></i>Free domains</li>
                    <li className="enable"><i className="ph-duotone ph-check-circle"></i>CDN Integration</li>
                    <li className="enable"><i className="ph-duotone ph-check-circle"></i>Advanced Settings</li>
                    <li className="enable"><i className="ph-duotone ph-check-circle"></i>100,000 unique users</li>
                    <li className="enable"><i className="ph-duotone ph-check-circle"></i>2000 Items</li>
                    <li className="enable"><i className="ph-duotone ph-check-circle"></i>API Access</li>
                    <li className="enable"><i className="ph-duotone ph-check-circle"></i>Search Features</li>
                    <li className="enable"><i className="ph-duotone ph-check-circle"></i>Editor personalization</li>
                    <li className="enable"><i className="ph-duotone ph-check-circle"></i>Upload special sites</li>
                    <li className="enable"><i className="ph-duotone ph-check-circle"></i>Advanced Features</li>
                  </ul>
                  <div className="d-grid">
                    <button className="btn btn-outline-secondary">Upgrade Plan</button>
                  </div>
                </Card.Body>
              </Card>
            </Col>
          </Row>
        </Col>
        </Row>
       </>
    )
}

Plans.getLayout = (page: ReactElement) => {
    return (
      <Layout>
        {page}
      </Layout>
    )
};


export default Plans
